CREATE INDEX ARTICLE_CATEGORY ON ARTICLE (CATEGORY ASC);
CREATE INDEX BIGRAM_WORD1 ON BIGRAM (WORD1 ASC);
CREATE UNIQUE INDEX BIGRAM1 ON BIGRAM (WORD1 ASC, WORD2 ASC);
CREATE INDEX BW_BIGRAM_ID ON SENTENCE_BIGRAM (BIGRAM_ID ASC);
CREATE INDEX SW_SENTENCE_ID ON SENTENCE_WORD (SENTENCE_ID ASC);
CREATE INDEX SW_WORD_ID ON SENTENCE_WORD (WORD_ID ASC);
CREATE INDEX TRIGRAM1 ON TRIGRAM (WORD1 ASC, WORD2 ASC, WORD3 ASC);
CREATE INDEX TW_TRIGRAM_ID ON SENTENCE_TRIGRAM (TRIGRAM_ID ASC);
CREATE INDEX WORD_VAL ON WORD (VAL ASC);