Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115861,'දෙරණ ඩ්‍රීම් ස්ටාර් සීසන් ෆෝ කිරුළ සසිඳුට',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115862,'මුහුදට වැටුණු තරුණයා අතුරුදහන්',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115863,'ජගත් දූෂණ විරෝධී දිනය අදයි!',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115864,'අතීතය ගොඩගනියි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115865,'කච්චේරි ගින්නේ වාර්තා තවමත් නෑ',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115866,'ලයිලා සුරුක්කු ආයෙත් ඇවිත්',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115867,'ගල්කටස් 2ක් සමග දැලේ',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115868,'අම්පාර යළිත් හෙ‍ල්ලෙයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115869,'දික්වැල්ලේ නිවසකින් පාසල් පෙළපොත් තොගයක් හමුවෙයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115870,'ඉන්දියාව තෙවැනි ටෙස්ට් තරගයත් පරාදවෙයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115871,'මැන්ඩෙලා රෝහල්ගත කරයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115872,'ගව හොරෙක් අල්ලයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115873,'අන්තර්ජාල බද්ද 50% න් පහලට',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115874,'ඔස්ට්‍රේලියාවෙන් පැපුවා නිව් ගිනියාවට යවයි',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115875,'පාර්ලිමේන්තුවේ භාෂා පරිවර්තකයෙක්ට මන්ත්‍රීවරයෙක් පහරදීලා',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115876,'ආණ්ඩුව බලය වෙනුවෙන් ඕනෑම ලැජ්ජ නැති වැඩක් කරනවා',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115877,'අධිකරණය දෙකඩ කොට දේශපාලනීකරණය කිරීමේ උත්සහයක් තිබෙනවා',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115878,'ඇමතිවරු දෙ‍න්නෙක් අගවිනිසුරුවරියට පහත් ආකාරයෙන් කතා කළා',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115879,'දිවිනැඟුම පනතේ තීන්දුව නිසා තමයි මෙහෙම වුණේ',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115880,'හොරට දැව ඉරූ 3ක් මාට්ටු',null,'NEWS',null,2012,12,9);
Insert into ARTICLE (ID,TOPIC,AUTHOR,CATEGORY,SUBCAT1,YEAR,MONTH,DAY) values (115881,'අද අස්ථි කොටස් හමුවුණේ නෑ',null,'NEWS',null,2012,12,9);
